development:
  sessions:
    default:
      database: muser_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: muser_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: muser_production
      hosts:
        - 176.58.109.95:27017
  options:
    raise_not_found_error: false